from pathlib import Path
import re
r=Path('target/installed-disk-validation/installed-memory-callers/complete-600c0ca/proposed/crates/kasumi-server/src')
p=r/'serving_task_drain_tests.rs';s=p.read_text()
s=re.sub(r'(\s*)let path = directory.path\(\).join\("([^"]+)"\);',lambda m:f'{m[1]}let physical = crate::runtime_storage_fixtures::physical(directory.path(), Default::default()).unwrap();{m[1]}let path = directory.path().join("persistent/{m[2]}");',s)
s=re.sub(r'kasumi_store::NodeStore::(create_new|open_existing)_fixture\(\s*&path,\s*kasumi_store::test_utils::NODE_STORE_ID,\s*kasumi_store::ScratchDisk::fixture\(\),?\s*\)',r'physical.\1(&path, kasumi_store::test_utils::NODE_STORE_ID)',s)
s=s.replace('let _node = node;\n        waiting.await?;', 'waiting.await?;\n        node.shutdown().await?;')
s=s.replace('let _node = node;\n        retained.await?;', 'retained.await?;\n        node.shutdown().await?;')
s=s.replace('        request.release.notified().await;','        request.release.notified().await;\n        request._node.shutdown().await.unwrap();')
s=s.replace('    drop(reopened);','    reopened.shutdown().await.unwrap();')
s=s.replace('    let _reopened = physical.open_existing','    let reopened = physical.open_existing')
s=re.sub(r'(let reopened = physical\.open_existing\(&path, kasumi_store::test_utils::NODE_STORE_ID\)\s*\.unwrap\(\);)(?!\s*reopened.shutdown)',r'\1\n        reopened.shutdown().await.unwrap();',s)
p.write_text(s)
p=r/'target_runtime_shutdown_tests.rs';s=p.read_text()
s=s.replace('let path = directory.path().join("target-journal.redb");','let physical = crate::runtime_storage_fixtures::physical(directory.path(), Default::default()).unwrap();\n        let path = directory.path().join("persistent/target-journal.redb");')
s=s.replace('NodeStore::create_new_fixture(&path, node_id, kasumi_store::ScratchDisk::fixture())','physical.create_new(&path, node_id)')
s=s.replace('let admission = NodeAdmission::new(Default::default()).unwrap();','let admission = physical.admission.clone();')
s=s.replace('directory.path().join("partial-target.redb")','directory.path().join("persistent/partial-target.redb")')
s=s.replace('NodeStore::create_new_fixture(\n            &partial_path,\n            partial_id,\n            kasumi_store::ScratchDisk::fixture(),\n        )','physical.create_new(&partial_path, partial_id)')
s=s.replace('        drop(\n            NodeStore::open_existing_fixture(\n                &partial_path,\n                partial_id,\n                kasumi_store::ScratchDisk::fixture(),\n            )\n            .unwrap(),\n        );','        physical.open_existing(&partial_path, partial_id).unwrap().shutdown().await.unwrap();')
s=s.replace('NodeStore::open_existing_fixture(&path, node_id, kasumi_store::ScratchDisk::fixture())','physical.open_existing(&path, node_id)')
s=s.replace('TenantStore::open_existing(reopened, journal_tenant, provider, access)','TenantStore::open_existing(reopened.clone(), journal_tenant, provider, access)')
s=s.replace('        store.shutdown().await.unwrap();','        store.shutdown().await.unwrap();\n        reopened.shutdown().await.unwrap();')
s=s.replace('let path = directory.path().join("unpublished-target.redb");','let physical = crate::runtime_storage_fixtures::physical(directory.path(), Default::default()).unwrap();\n        let path = directory.path().join("persistent/unpublished-target.redb");')
s=s.replace('NodeStore::create_new_fixture(&path, id, kasumi_store::ScratchDisk::fixture())','physical.create_new(&path, id)')
s=s.replace('NodeStore::claim_cleanup_fixture(&path, id)','NodeStore::claim_cleanup(&path, id, physical.persistent.clone())')
s=s.replace('        std::fs::remove_file(&path).unwrap();\n        kasumi_store::private_files::sync_parent(&path).unwrap();\n        drop(ownership);','        ownership.delete().unwrap();')
p.write_text(s)
