from pathlib import Path
p=Path('/Users/mtakemiya/dev/kasumi/target/installed-disk-validation/directory-cursor/proposed/crates/kasumi-store/src')
q=p/'node_disk.rs';s=q.read_text();s=s.replace('pub use directory::NodeDiskDirectory;','pub use directory::{NodeDiskDirectory, NodeDiskDirectoryCursor, NodeDiskDirectoryEntry, NodeDiskEntryKind};');s=s.replace('/// Cancellation affects only unpublished census work; it grants no storage access.','/// Cancellation affects bounded directory reads and unpublished census work;\n/// it grants no storage access.');s=s.replace('    pub open_directories: u32,','    pub open_directories: u32,\n    pub open_directory_cursors: u32,');s=s.replace('    open_directories: u32,','    open_directories: u32,\n    open_directory_cursors: u32,\n    namespace_generation: u64,');s=s.replace('                open_directories: 0,','                open_directories: 0,\n                open_directory_cursors: 0,\n                namespace_generation: 0,');s=s.replace('snapshot.open_files == 0 && snapshot.open_directories == 0','snapshot.open_files == 0 && snapshot.open_directories == 0 && snapshot.open_directory_cursors == 0');s=s.replace('            open_directories: state.open_directories,','            open_directories: state.open_directories,\n            open_directory_cursors: state.open_directory_cursors,');s=s.replace('state.open_files == 0 && state.open_directories == 0','state.open_files == 0 && state.open_directories == 0 && state.open_directory_cursors == 0');q.write_text(s)
q=p/'node_disk/namespace.rs';s=q.read_text().replace('pub(super) struct ParentTransition {\n    changes:', 'pub(super) struct ParentTransition {\n    generation: u64,\n    changes:');needle='        if let Some(work) = growth_work {';s=s.replace(needle,'        let generation = state.namespace_generation.checked_add(1).ok_or(io::ErrorKind::StorageFull)?;\n'+needle);s=s.replace('        Ok(Self { changes })','        Ok(Self { generation, changes })');s=s.replace('        state.bytes = bytes;','        state.namespace_generation = self.generation;\n        state.bytes = bytes;');q.write_text(s)
q=p/'node_disk/directory.rs';s=q.read_text();s+='\nmod cursor;\npub use cursor::{NodeDiskDirectoryCursor, NodeDiskDirectoryEntry, NodeDiskEntryKind};\n';q.write_text(s)
q=p/'lib.rs';s=q.read_text();s=s.replace('NodeDiskDirectory,','NodeDiskDirectory, NodeDiskDirectoryCursor, NodeDiskDirectoryEntry, NodeDiskEntryKind,');q.write_text(s)
q=p/'node_disk/memory.rs';s=q.read_text();needle='        let cursors = mul(';s=s.replace(needle,'''        // Operational cursors retain counted DirectoryOwners, so a census may
        // not overlap them. At most max_depth operational streams reuse these
        // existing census slots. This does not qualify the underlying native
        // stream allowance or the separate table-growth estimate.
        if size::<directory::NodeDiskDirectoryCursor>()? > mul(4, size::<census::Cursor>()?)? {
            return Err(io::ErrorKind::InvalidData.into());
        }
'''+needle);q.write_text(s)
